### ISSUE TITLE
Always redirecting to Google Play Store

### ISSUE THREAD

**Issue by steve-pires** [GeekyAnts/external_app_launcher#3]
Plugin is always opening Google Play Store even if the app is installed on the phone (Play Store page is the correct app with "Open" button, not "Install").

Debug console prints out:
`I/flutter (11386): Redirecting to Google Play Store as the app is not present on the device
`

Tested on a OnePlus 8T under Android 11 / Oxygen OS 11.0.11.11

**Comment by RoySis** [comment]
add the following line inside the <manifest> tag in the AndroidManifest.xml file:

<manifest...>
    <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />
</manifest>

it worked for me :-)

**Comment by steve-pires** [comment]
Worked like a charm thanks ! (and sorry I'm a newbie on Flutter / mobile dev)

**Comment by ritwiktakkar** [comment]
the play store may likely reject a submission with the permission @RoySis added because sufficient functionality can usually be achieved without the extensive visibility QUERY_ALL_PACKAGES provides - though YMMV. Refer to this answer for a more acceptable solution: https://stackoverflow.com/a/78669594/12664030
